app = "imagetagger"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile.fly"

[env]
  DJANGO_SETTINGS_MODULE = "imagetagger.settings"
  DJANGO_CONFIGURATION = "Prod"
  IT_ALLOWED_HOSTS = ".fly.dev"
  IT_DOWNLOAD_BASE_URL = "https://imagetagger.fly.dev"
  IT_EMAIL_HOST = "localhost"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
