databases:
  - name: imagetagger-db
    plan: free
    databaseName: imagetagger
    user: imagetagger

services:
  - type: web
    name: imagetagger
    runtime: python
    buildCommand: bash build.sh
    startCommand: cd src && gunicorn imagetagger.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: imagetagger.settings
      - key: DJANGO_CONFIGURATION
        value: Prod
      - key: PYTHON_VERSION
        value: "3.12.2"
      - key: IT_SECRET_KEY
        generateValue: true
      - key: IT_ALLOWED_HOSTS
        value: .onrender.com
      - key: IT_DOWNLOAD_BASE_URL
        sync: false
      - key: IT_EMAIL_HOST
        value: localhost
      - key: IT_DB_HOST
        fromDatabase:
          name: imagetagger-db
          property: host
      - key: IT_DB_PORT
        fromDatabase:
          name: imagetagger-db
          property: port
      - key: IT_DB_NAME
        fromDatabase:
          name: imagetagger-db
          property: database
      - key: IT_DB_USER
        fromDatabase:
          name: imagetagger-db
          property: user
      - key: IT_DB_PASSWORD
        fromDatabase:
          name: imagetagger-db
          property: password
